In [1]:
import pandas as pd

In [41]:
batch = pd.read_csv("last batch.csv").drop(["time", "sunrise (iso8601)", "sunset (iso8601)"], axis=1)
batch

,location_id,temperature_2m_max (°F),temperature_2m_min (°F),daylight_duration (s),sunshine_duration (s),uv_index_max (),precipitation_sum (inch),rain_sum (inch),showers_sum (inch),snowfall_sum (inch),precipitation_hours (h),wind_speed_10m_max (mp/h),wind_gusts_10m_max (mp/h),shortwave_radiation_sum (MJ/m²)
0,0,44.5,36.6,32919.72,0.00,2.10,0.000,0.000,0,0,0,9.3,19.0,2.92
1,0,45.3,37.1,32967.80,4532.35,2.25,0.000,0.000,0,0,0,5.3,11.4,5.11
2,0,42.6,37.2,33020.16,0.00,0.25,0.244,0.244,0,0,6,9.8,19.5,0.82
3,0,56.6,41.0,33076.70,0.00,1.00,0.201,0.201,0,0,3,10.5,19.5,2.31
4,0,48.2,36.1,33137.29,9396.66,1.55,0.000,0.000,0,0,0,14.4,26.2,5.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,95,64.2,39.9,35802.52,32371.92,3.60,0.000,0.000,0,0,0,5.7,9.4,13.11
35036,95,67.5,41.5,35820.80,32400.00,3.80,0.000,0.000,0,0,0,5.6,7.4,12.71
35037,95,71.2,41.5,35842.15,32400.00,3.75,0.000,0.000,0,0,0,5.7,12.8,12.82
35038,95,72.9,50.1,35866.49,25200.00,3.65,0.000,0.000,0,0,0,6.7,16.6,11.68
35039,95,70.0,46.4,35893.78,31499.78,3.60,0.000,0.000,0,0,0,5.7,15.7,12.16

In [42]:
batch["daylight_duration (s)"] = batch["daylight_duration (s)"] / 3600
batch["sunshine_duration (s)"] = batch["sunshine_duration (s)"] / 3600

In [43]:
gb = batch.groupby("location_id").mean().reset_index()
gb = gb.add_suffix('_mean')
gb

,location_id_mean,temperature_2m_max (°F)_mean,temperature_2m_min (°F)_mean,daylight_duration (s)_mean,sunshine_duration (s)_mean,uv_index_max ()_mean,precipitation_sum (inch)_mean,rain_sum (inch)_mean,showers_sum (inch)_mean,snowfall_sum (inch)_mean,precipitation_hours (h)_mean,wind_speed_10m_max (mp/h)_mean,wind_gusts_10m_max (mp/h)_mean,shortwave_radiation_sum (MJ/m²)_mean
0,0,60.753973,44.606575,12.214273,6.795859,4.436027,0.078627,0.078627,0.0,0.0,1.224658,12.002192,22.936438,14.715151
1,1,60.695068,46.290137,12.210295,7.018551,4.550000,0.076704,0.076704,0.0,0.0,1.150685,14.168767,23.789589,15.196658
2,2,79.439452,57.903836,12.174983,8.460266,6.119726,0.101145,0.101145,0.0,0.0,0.832877,9.976986,18.610959,18.065260
3,3,75.773425,55.972603,12.178718,8.260082,5.893562,0.077468,0.077468,0.0,0.0,0.824658,9.355068,19.443836,17.941534
4,4,79.438904,59.638356,12.175494,8.420841,5.972740,0.115329,0.115329,0.0,0.0,0.876712,10.190959,19.735890,18.279479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,91,76.903014,50.296164,12.193568,9.320499,5.679315,0.042959,0.042959,0.0,0.0,0.600000,10.713699,19.936438,19.349808
92,92,66.352329,49.969315,12.202341,7.667005,4.909041,0.146860,0.146860,0.0,0.0,1.016438,10.835616,21.795342,16.253973
93,93,61.973425,45.146849,12.242328,6.244136,4.071918,0.057082,0.057082,0.0,0.0,1.569863,9.524110,18.183014,13.355014
94,94,60.675068,43.088493,12.217627,7.102854,4.373151,0.158981,0.158981,0.0,0.0,1.687671,10.836712,22.112055,14.777918
95,95,88.231233,64.561644,12.178412,10.042629,6.576164,0.011025,0.011025,0.0,0.0,0.172603,9.133425,17.349315,21.574795

In [44]:
# gb.to_csv("first_batch_means.csv")
gb.to_csv("last_batch_means.csv")